demo/urls.py
# -*- coding: UTF-8 -*-
"""
@File: urls.py
@Description:
@Author: Xuan Li(6732409)
@DateTime: 18/12/2022 18:50 
@Project_name: djangoProject
@IDE: PyCharm 
"""
from django.urls import path

from . import views

app_name='demo'
urlpatterns=[
    path("",views.index, name="demo"),
    path("addinfo/", views.addInfo, name="addinfo"),
    path("saveinfo/", views.saveInfo, name="saveinfo"),
    path("deteteinfo/<int:id>", views.deteteinfo, name="deteteinfo"),
    path("updateinfo/<int:id>", views.updateInfo, name="updateinfo"),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.views import static

from djangoProject import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('runoob/', views.index),
    path('polls/', include('polls.urls')),
    path('rent/',include('rent.urls')),
    re_path(r'^static/(?P<path>.*)$', static.serve,
      {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^medias/(?P<path>.*)$', static.serve, 
        {'document_root': settings.MEDIA_ROOT})

]

demo/models.py
from django.db import models
from django.db.models import AutoField, CharField, IntegerField, DateTimeField


# Create your models here.
class DemoModel(models.Model):
    id=AutoField(primary_key=True)
    first_name=CharField(max_length=100)
    last_name=CharField(max_length=100)
    age=IntegerField(default=0)
    gender=CharField(default="male",null=False, max_length=20)
    create_time = DateTimeField(auto_now_add=True)
    create_user = CharField(max_length=100)
    update_time = DateTimeField(auto_now=True)
    update_user = CharField(max_length=100)
    is_deleted = IntegerField(default=0)

demo/templates/demo/addInfo.html
<div class="container">
    <form method="post" action="{% url "demo:saveinfo" %}">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ demo.id }}">
        <table class="table table-borderless table-sm align-middle caption-top">
            <caption><h2>input info</h2></caption>
            <tr>
                <td colspan="2">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="firstName" name="first_name"value="{{ demo.first_name }}">
                        <label for="firstName">First Name</label>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="lastName" name="last_name"value="{{ demo.last_name }}">
                        <label for="lastName">Last Name</label>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="form-floating mb-3">
                        <input type="number" class="form-control" id="age" name="age"value="{{ demo.age }}">
                        <label for="age">Age</label>
                    </div>
                </td>        
            </tr>
            <tr>
                <td>Gender:</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" id="gender1" value="male" 
                        {% if demo.gender == "male" %}checked{% endif %}>
                        <label class="form-check-label" for="gender1">
                            male
                        </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" id="gender2" value="female" 
                        {% if demo.gender == "female" %} checked{% endif %}>
                        <label class="form-check-label" for="gender2">
                            female
                        </label>
                      </div>
                </td>
            </tr>
            <tr >
                <td colspan="2"><button type="submit" class="btn btn-primary ">save</button></td>
            </tr>

        </table>
        
    </form>
<div>

demo/templates/demo/info.html
<div class="container">
    <table class="table table-striped">
        <caption>demo info</caption>
        <tr>
            <th>choose</th>
            <th>id</th>
            <th>firstName</th>
            <th>lastName</th>
            <th>age</th>
            <th>gender</th>
            <th>detete info</th>
            <th>update info</th>
        </tr>
        {% for x in demos %}
        <tr id="info{{ x.id }}">
            <td><input type="radio" name="info"></td>
            <td>{{ x.id }}</td>
            <td>{{ x.first_name }}</td>
            <td>{{ x.last_name }}</td>
            <td>{{ x.age }}</td>
            <td>{{ x.gender }}</td>
            <td><a href="{% url "demo:deteteinfo" x.id %}" class="btn btn-warning btn-sm">detete info</a></td>
            <td><a href="{% url "demo:updateinfo" x.id %}" class="btn btn-primary btn-sm">update info</a></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url "demo:addinfo" %}" class="btn btn-info" role="button">add info</a>
</div>