demo/urls.py
# -*- coding: UTF-8 -*-
"""
@File: urls.py
@Description:
@Author: Xuan Li(6732409)
@DateTime: 18/12/2022 18:50 
@Project_name: djangoProject
@IDE: PyCharm 
"""
from django.urls import path

from . import views

app_name='demo'
urlpatterns=[
    path("",views.index, name="demo"),
    path("addinfo/", views.addInfo, name="addinfo"),
    path("saveinfo/", views.saveInfo, name="saveinfo"),
    path("deteteinfo/<int:id>", views.deteteinfo, name="deteteinfo"),
    path("updateinfo/<int:id>", views.updateInfo, name="updateinfo"),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.views import static

from djangoProject import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('runoob/', views.index),
    path('polls/', include('polls.urls')),
    path('rent/',include('rent.urls')),
    re_path(r'^static/(?P<path>.*)$', static.serve,
      {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^medias/(?P<path>.*)$', static.serve, 
        {'document_root': settings.MEDIA_ROOT})

]

rent/urls.py
# -*- coding: UTF-8 -*-
"""
@File: urls.py
@Description:
@Author: Xuan Li(6732409)
@DateTime: 18/12/2022 18:50 
@Project_name: djangoProject
@IDE: PyCharm 
"""
from django.urls import path

from . import views

app_name='rent'
urlpatterns=[
    path("",views.index, name="rent"),
    path("bill/",views.bill, name="bill"),
    path("addinfo/", views.addInfo, name="addinfo"),
    path("saveinfo/", views.saveInfo, name="saveinfo"),
    path("deteteinfo/<int:id>", views.deteteinfo, name="deteteinfo"),
    path("updateinfo/<int:id>", views.updateInfo, name="updateinfo"),
]

rent/models.py
from django.db import models
from django.db.models import AutoField, CharField, IntegerField, DateTimeField,DateField


# Create your models here.
class RentModel(models.Model):
    id=AutoField(primary_key=True)
    first_name=CharField(max_length=100)
    last_name=CharField(max_length=100)
    age=IntegerField(default=0)
    gender=CharField(default="male",null=False, max_length=20)
    create_time = DateTimeField(auto_now_add=True)
    create_user = CharField(max_length=100)
    update_time = DateTimeField(auto_now=True)
    update_user = CharField(max_length=100)
    is_deleted = IntegerField(default=0)

class Bill(models.Model):
    id=models.AutoField(primary_key=True)
    start_date=models.DateField(verbose_name="start_date")
    due_date=models.DateField(verbose_name="end_date")
    fee_aud=models.DecimalField(verbose_name="fee_aud",max_digits=7, decimal_places=2)
    fee_rmb=models.DecimalField(verbose_name="fee_rmb",max_digits=7, decimal_places=2)
    payment_date=models.DateField(verbose_name="payment_date")
    comments=models.CharField(null=True, max_length=1000, blank=True)
    create_time = DateTimeField(auto_now_add=True)
    create_user = CharField(max_length=100)
    update_time = DateTimeField(auto_now=True)
    update_user = CharField(max_length=100)
    is_deleted = IntegerField(default=0)

rent/views.py
import time

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from rent.models import RentModel,Bill


# Create your views here.
def bill(request):
    """
    bill history view parser
    """
    bills = Bill.objects.filter(is_deleted=0).values()
    total_fee_aud=sum([bill['fee_aud'] for bill in bills])
    total_fee_rmb=sum([bill['fee_rmb'] for bill in bills])
    return render(request, "rent/bill.html", {"bills": bills,"titleName":"bill", "total_fee_aud":total_fee_aud, "total_fee_rmb":total_fee_rmb})


def index(request):
    rents = RentModel.objects.filter(is_deleted=0).values()
    return render(request, "rent/index.html", {"rents": rents,"titleName":"rent", "context":"home"})

def addInfo(request):
    return render(request, "rent/index.html",{"titleName":"add info", "context":"addinfo"})

def saveInfo(request):
    info = {}
    for para in request.POST:
        info.setdefault(para, request.POST[para])
    if info['id'] == "":
        rent = RentModel(first_name=info["first_name"], last_name=info["last_name"], age=info["age"], gender=info["gender"],
                         create_user="zhangsan", update_user="zhangsan")
        rent.save()
    else:
        rent = RentModel.objects.get(id=info['id'])
        rent.first_name=info["first_name"]
        rent.last_name=info["last_name"]
        rent.age=info["age"]
        rent.gender=info["gender"]
        rent.update_time=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        rent.update_user=rent.first_name+rent.last_name
        rent.save()
    return HttpResponseRedirect(reverse("rent:rent"))

def deteteinfo(request, id):
    rent=RentModel.objects.get(id=id)
    rent.is_deleted=1
    rent.save()
    return HttpResponseRedirect(reverse("rent:rent"))

def updateInfo(request,id):
    rent=RentModel.objects.get(id=id)
    context={"rent": rent,"titleName":"update info", "context":"updateinfo"}
    return  render(request, "rent/index.html", context)

rent/templates/rent/addInfo.html
<div class="container">
    <form method="post" action="{% url "rent:saveinfo" %}">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ rent.id }}">
        <table class="table table-borderless table-sm align-middle caption-top">
            <caption><h2>input info</h2></caption>
            <tr>
                <td colspan="2">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="firstName" name="first_name"value="{{ rent.first_name }}">
                        <label for="firstName">First Name</label>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="lastName" name="last_name"value="{{ rent.last_name }}">
                        <label for="lastName">Last Name</label>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="form-floating mb-3">
                        <input type="number" class="form-control" id="age" name="age"value="{{ rent.age }}">
                        <label for="age">Age</label>
                    </div>
                </td>        
            </tr>
            <tr>
                <td>Gender:</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" id="gender1" value="male" 
                        {% if rent.gender == "male" %}checked{% endif %}>
                        <label class="form-check-label" for="gender1">
                            male
                        </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" id="gender2" value="female" 
                        {% if rent.gender == "female" %} checked{% endif %}>
                        <label class="form-check-label" for="gender2">
                            female
                        </label>
                      </div>
                </td>
            </tr>
            <tr >
                <td colspan="2"><button type="submit" class="btn btn-primary ">save</button></td>
            </tr>

        </table>
        
    </form>
<div>

rent/templates/rent/bill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {{ titleName }}</title>
    {% include "rent/css-tag.html" %}
    {% include "rent/style.html" %}
</head>
<body> 
    {% include "rent/billInfo.html" %}
    {% include "rent/js-tag.html" %}
   
</body>
</html>

rent/templates/rent/billInfo.html
<div class="container">
    <table class="table table-striped">
        <caption>Rent History</caption>
        <tr>
            {% comment %} <th>choose</th> {% endcomment %}
            <th>id</th>
            <th>Start Date</th>
            <th>Due Date</th>
            <th>Fee(AUD)</th>
            <th>Fee(RMB)</th>
            <th>Payment Date</th>
            <th>Comment</th>
        </tr>
        {% for x in bills %}
        <tr id="info{{ x.id }}">
            {% comment %} <td><input type="radio" name="info"></td> {% endcomment %}
            <td>{{ x.id }}</td>
            <td>{{ x.start_date|date:"Y/m/d" }}</td>
            <td>{{ x.due_date|date:"Y/m/d" }}</td>
            <td>${{ x.fee_aud }}</td>
            <td>￥{{ x.fee_rmb }}</td>
            <td>{{ x.payment_date|date:"Y/m/d" }}</td>
            <td>{{ x.comments|default_if_none:"" }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td>total</td>
            <td></td>
            <td></td>
            <td>{{ total_fee_aud }}</td>
            <td>{{ total_fee_rmb }}</td>
            <td></td>
            <td></td> 
        </tr>
    </table>
</div>

rent/templates/rent/billInfo_zh.html
<div class="container">
    <div class="float-start">
        <a href="{% url "rent:translate" "en" %}" class="link-primary"><img src="http://img2.3png.com/7941f13223399ee579a880ea99e071cceeae.png" width=20>EN</a>
        <a href="javascript:window.print();" class="link-info">打印</a>
        <a href="{% url "rent:export" %}" class="link-info">导出</a>
    </div>
    <div  class="float-end">
        <em>￥人民币->$澳元(来源: 招商银行):&nbsp;&nbsp;</em><strong id="exchange"></strong>
        <em>时间:&nbsp;&nbsp;</em><span id="time"></span> 
    </div>
    <table class="table table-striped">
        <caption>房租历史</caption>
        <tr>
            {% comment %} <th>choose</th> {% endcomment %}
            <th>序号</th>
            <th>开始日期</th>
            <th>截至日期</th>
            <th>费用(澳元)</th>
            <th>费用(人民币)</th>
            <th>支付日期</th>
            <th>说明</th>
        </tr>
        {% for x in bills %}
        <tr id="info{{ x.id }}">
            {% comment %} <td><input type="radio" name="info"></td> {% endcomment %}
            <td>{{ x.id }}</td>
            <td>{{ x.start_date|date:"Y/m/d" }}</td>
            <td>{{ x.due_date|date:"Y/m/d" }}</td>
            <td>A${{ x.fee_aud }}</td>
            <td>￥{{ x.fee_rmb }}</td>
            <td>{{ x.payment_date|date:"Y/m/d" }}</td>
            <td>{{ x.comments|default_if_none:"" }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td>合计</td>
            <td></td>
            <td></td>
            <td>A${{ total_fee_aud }}</td>
            <td>￥{{ total_fee_rmb }}</td>
            <td></td>
            <td></td> 
        </tr>
    </table>
</div>

rent/templates/rent/css-tag.html
<link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.min.css" rel="stylesheet">

rent/templates/rent/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {{ titleName }}</title>
    {% include "rent/css-tag.html" %}
    {% include "rent/style.html" %}
</head>
<body>
    {% if context == "home" %}
        {% include "rent/info.html" %}
    {% elif context == "addinfo" %}
        {% include "rent/addInfo.html" %}
    {% elif context == "updateinfo" %}
        {% include "rent/addinfo.html" %}
    {% endif %} 
    {% include "rent/js-tag.html" %}
   
</body>
</html>

rent/templates/rent/info.html
<div class="container">
    <table class="table table-striped">
        <caption>rent info</caption>
        <tr>
            <th>choose</th>
            <th>id</th>
            <th>firstName</th>
            <th>lastName</th>
            <th>age</th>
            <th>gender</th>
            <th>detete info</th>
            <th>update info</th>
        </tr>
        {% for x in rents %}
        <tr id="info{{ x.id }}">
            <td><input type="radio" name="info"></td>
            <td>{{ x.id }}</td>
            <td>{{ x.first_name }}</td>
            <td>{{ x.last_name }}</td>
            <td>{{ x.age }}</td>
            <td>{{ x.gender }}</td>
            <td><a href="{% url "rent:deteteinfo" x.id %}" class="btn btn-warning btn-sm">detete info</a></td>
            <td><a href="{% url "rent:updateinfo" x.id %}" class="btn btn-primary btn-sm">update info</a></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url "rent:addinfo" %}" class="btn btn-info" role="button">add info</a>
</div>

rent/templates/rent/js-tag.html
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.min.js"></script>

rent/templates/rent/style.html
<style>
    caption {
        text-align: center;
        font-size: 50px;
        caption-side: top;
    }
</style>